### ISSUE TITLE
Comparison with other state-of-the-art methods

### ISSUE THREAD

**Issue by hugochan** [jdongca2003/next_utterance_selection#1]
Hi,

Thank you for releasing the code! I enjoyed reading your paper. I was wondering how is your method compared to other state-of-the-art methods such as [SMN](https://arxiv.org/pdf/1612.01627.pdf). In your paper, you mentioned their published results were not directly comparable to yours since they were evaluated on UDC v1 instead of UDC v2. I was wondering if you have got a chance to evaluate them on UDC v2 after that so that they can be directly comparable to yours. Thank you for your time!

**Comment by jdongca2003** [comment]
Thank for interest. I did not have their code. I just referenced their results from their paper. If I implement them, it may not be fair to the original authors since I am not sure whether I use the correct parameters.
